export const mockProducts = [
  {
    id: "1",
    name: "Camiseta Básica Blanca",
    price: 25000,
    originalPrice: 30000,
    image: "/placeholder.svg?height=400&width=300",
    category: "hombre",
    stock: 15,
    sizes: ["S", "M", "L", "XL"],
    isNew: false,
    isSale: true,
    description: "Camiseta básica de algodón 100% en color blanco. Perfecta para el día a día.",
  },
  {
    id: "2",
    name: "Jeans Slim Fit Azul",
    price: 45000,
    image: "/placeholder.svg?height=400&width=300",
    category: "hombre",
    stock: 8,
    sizes: ["28", "30", "32", "34", "36"],
    isNew: true,
    isSale: false,
    description: "Jeans de corte slim fit en denim azul clásico. Cómodos y versátiles.",
  },
  {
    id: "3",
    name: "Vestido Floral Verano",
    price: 35000,
    image: "/placeholder.svg?height=400&width=300",
    category: "mujer",
    stock: 12,
    sizes: ["XS", "S", "M", "L"],
    isNew: true,
    isSale: false,
    description: "Vestido ligero con estampado floral, perfecto para el verano.",
  },
  {
    id: "4",
    name: "Chaqueta de Cuero Negro",
    price: 85000,
    originalPrice: 100000,
    image: "/placeholder.svg?height=400&width=300",
    category: "mujer",
    stock: 5,
    sizes: ["S", "M", "L"],
    isNew: false,
    isSale: true,
    description: "Chaqueta de cuero genuino en color negro. Estilo clásico y atemporal.",
  },
  {
    id: "5",
    name: "Sneakers Deportivos",
    price: 55000,
    image: "/placeholder.svg?height=400&width=300",
    category: "accesorios",
    stock: 20,
    sizes: ["38", "39", "40", "41", "42", "43"],
    isNew: true,
    isSale: false,
    description: "Sneakers deportivos cómodos y modernos. Ideales para el día a día.",
  },
  {
    id: "6",
    name: "Bolso de Mano Elegante",
    price: 40000,
    image: "/placeholder.svg?height=400&width=300",
    category: "accesorios",
    stock: 7,
    sizes: ["Único"],
    isNew: false,
    isSale: false,
    description: "Bolso de mano elegante en cuero sintético. Perfecto para ocasiones especiales.",
  },
  {
    id: "7",
    name: "Camisa Formal Blanca",
    price: 32000,
    image: "/placeholder.svg?height=400&width=300",
    category: "hombre",
    stock: 18,
    sizes: ["S", "M", "L", "XL", "XXL"],
    isNew: false,
    isSale: false,
    description: "Camisa formal de algodón en color blanco. Ideal para el trabajo.",
  },
  {
    id: "8",
    name: "Falda Midi Negra",
    price: 28000,
    originalPrice: 35000,
    image: "/placeholder.svg?height=400&width=300",
    category: "mujer",
    stock: 10,
    sizes: ["XS", "S", "M", "L", "XL"],
    isNew: false,
    isSale: true,
    description: "Falda midi en color negro. Versátil y elegante para cualquier ocasión.",
  },
  {
    id: "9",
    name: "Reloj Clásico",
    price: 75000,
    image: "/placeholder.svg?height=400&width=300",
    category: "accesorios",
    stock: 3,
    sizes: ["Único"],
    isNew: true,
    isSale: false,
    description: "Reloj clásico con correa de cuero. Elegancia y precisión en tu muñeca.",
  },
  {
    id: "10",
    name: "Sudadera con Capucha",
    price: 38000,
    image: "/placeholder.svg?height=400&width=300",
    category: "hombre",
    stock: 14,
    sizes: ["S", "M", "L", "XL"],
    isNew: false,
    isSale: false,
    description: "Sudadera cómoda con capucha. Perfecta para días casuales y relajados.",
  },
  {
    id: "11",
    name: "Blusa Seda Rosa",
    price: 42000,
    image: "/placeholder.svg?height=400&width=300",
    category: "mujer",
    stock: 6,
    sizes: ["XS", "S", "M", "L"],
    isNew: true,
    isSale: false,
    description: "Blusa de seda en tono rosa suave. Elegante y sofisticada.",
  },
  {
    id: "12",
    name: "Gafas de Sol",
    price: 22000,
    originalPrice: 28000,
    image: "/placeholder.svg?height=400&width=300",
    category: "accesorios",
    stock: 25,
    sizes: ["Único"],
    isNew: false,
    isSale: true,
    description: "Gafas de sol con protección UV. Estilo y protección para tus ojos.",
  },
]
